[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
      \.env
    | \.venv
    | \.git
    | \.idea
  )/
)
'''

[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 79

[tool.mypy]
ignore_missing_imports = true
warn_no_return = false
disable_error_code = [
    "type-arg",
]

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "tests",
    "app/tests/",
    "app/utils/tests/",
    "alembic",
]
per-file-ignores = {}

# Same as Black.
line-length = 88

# Assume Python 3.11.
target-version = "py311"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.pytest.ini_options]
minversion = "6.0"
asyncio_mode = "auto"
addopts = "--maxfail=1 -v -s --cov=./ --disable-pytest-warnings"
testpaths = [
    "app/tests/",
    "app/utils/tests/",
]

[tool.pyright]
openFilesOnly = false
